import type { Metadata } from 'next'
import { Playfair_Display, Readex_Pro } from 'next/font/google'
import './globals.css'

const playfair = Playfair_Display({ subsets: ['latin'], weight: ['700'] })
const readex = Readex_Pro({ subsets: ['latin'], weight: ['700'], variable: '--font-readex' })

export const metadata: Metadata = {
  title: 'Vyre',
  description: 'Generated by Machine',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${playfair.className} ${readex.variable}`}>{children}</body>
    </html>
  )
}
